version: 0.2

env:
  parameter-store:
    AWS_REGION: "/agc/aws-region"
    ECR_REPOSITORY_URL: "/agc/ecr-repo-url"
    PROJECT_NAME: "/agc/project_name"
    APP_PORT: "/agc/app_port"
    DOCKER_USERNAME: "/agc/docker-hub-username"
    DOCKER_PASSWORD: "/agc/docker-hub-password"
    SSM_AUTOMATION_DOCUMENT_NAME: "/agc/automation-document-name"
    SSM_AUTOMATION_ROLE_ARN: "/agc/automation-role-arn"
    ASG_NAME: "/agc/asg-name"

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - echo Logging in to Amazon ECR...
      - echo $AWS_REGION $ECR_REPOSITORY_URL
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URL

  build:
    commands:
      - echo Building Docker image for app Service on port $APP_PORT...
      # - docker build --build-arg app_port=$APP_PORT -t app .
      # - docker tag app:latest $ECR_REPOSITORY_URL/agc/app:v1
      # - docker push $ECR_REPOSITORY_URL/agc/app:v1

  post_build:
  commands:
    - echo "Starting SSM automation execution..."
    - aws ssm start-automation-execution \
        --document-name "$SSM_AUTOMATION_DOCUMENT_NAME" \
        --document-version "\$DEFAULT" \
        --parameters "{\"AutomationAssumeRole\":[\"$SSM_AUTOMATION_ROLE_ARN\"],\"ASGName\":[\"$ASG_NAME\"]}" \
        --region "$AWS_REGION"
